- name: add java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: install java
  apt: name=oracle-java8-installer state=present

- name: Add Logstash Repo Key
  apt_key: url='https://packages.elasticsearch.org/GPG-KEY-elasticsearch' state=present

- name: add Logstash repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/2.0/debian stable main' state=present

- name: Install Logstash
  apt: pkg=logstash
       state=latest

- name: Create PKI folder
  file: path=/etc/logstash/pki
        state=directory
        owner=logstash
        group=logstash
        mode=u+r

- name: Install certificate
  shell: echo "{{logstash_cert}}" > /etc/logstash/pki/logstash-forwarder.crt

- name: Install key
  shell: echo "{{logstash_key}}" > /etc/logstash/pki/logstash-forwarder.key

- name: Set cert permissions
  file: path=/etc/logstash/pki/logstash-forwarder.crt
        owner=logstash
        group=logstash
        mode=u+r

- name: Set key permissions
  file: path=/etc/logstash/pki/logstash-forwarder.key
        owner=logstash
        group=logstash
        mode=u+r

- name: Configure default settings for Logstash
  template: src=logstash.conf.j2
            dest=/etc/logstash/conf.d/logstash.conf
            owner=logstash
            group=logstash
            mode=0644

- name: Create Logstash service
  copy: src=logstash_service
        dest=/etc/init.d/logstash
        mode=u+rwx
  notify:
   - restart logstash

