- name: add java repository
  apt_repository: repo='ppa:webupd8team/java' state=present

- name: install java
  apt: name=oracle-java8-installer state=present

- name: Add Logstash Repo Key
  apt_key: url='https://packages.elasticsearch.org/GPG-KEY-elasticsearch' state=present

- name: add Logstash repository
  apt_repository: repo='deb http://packages.elasticsearch.org/logstash/1.5/debian stable main' state=present

- name: Install Logstash
  apt: pkg=logstash state=latest

- name: Configure default settings for Logstash
  template: src=logstash.conf.j2
            dest=/etc/logstash/conf.d/logstash.conf
            owner=logstash
            group=logstash
            mode=0644
  notify:
   - restart logstash

