- hosts: all
  vars_files:
    - 'vars/creds.yml'
    - 'vars/versions.yml'
  roles:
    - {role: base,          tags: ['base']}
    - {role: logstash,      tags: ['logstash']}
    - {role: elasticsearch, tags: ['elasticsearch']}
    - {role: kibana,        tags: ['kibana']}
    - {role: nginx,         tags: ['nginx']}
