- name: Download Kibana
  get_url: url=https://download.elasticsearch.org/kibana/kibana/{{kibana_version_arch}}.tar.gz
           dest=/usr/local/src/{{kibana_version_arch}}.tar.gz
           force=no

- name: Check current version of kibana
  shell: grep -c '{{kibana_version}}' /opt/kibana/README.txt | wc -l
  register: version_match

- name: Remove old version of Kibana
  file: path=/opt/kibana
        state=absent
  when: version_match.stdout != "1"

- name: Extract and install Kibana
  unarchive: src=/usr/local/src/{{kibana_version_arch}}.tar.gz
             dest=/opt
             copy=no
             creates=/opt/{{kibana_version_arch}}
  when: version_match.stdout != "1"

- name: Rename extracted folder
  command: mv /opt/{{kibana_version_arch}} /opt/kibana
  when: version_match.stdout != "1"

- name: Configure default settings for Kibana
  template: src=kibana.yml.j2
            dest=/opt/kibana/config/kibana.yml
            mode=u+r

- name: Create Kibana service
  template: src=kibana_service.j2
            dest=/etc/init.d/kibana4
            mode=u+rwx
  notify:
  - restart kibana
